"""PR title/body + diffstat formatting and configurable committer
identity for the delivery orchestrator.

Covers:
- ``format_commit_message`` produces a sectioned markdown body with
  Summary / What changed / Verification / Provenance, and a clean
  title free of internal target jargon.
- ``_diffstat`` summarizes a unified diff.
- The config loader defaults the committer identity to
  "Fred [bot]" / "github@dragonflybsd.org" and honors overrides.
"""

from __future__ import annotations

from pathlib import Path

from dportsv3.delivery.config import load_delivery_config
from dportsv3.delivery.orchestrator import (
    format_pr_body,
    _diffstat,
    _md_inline,
    _md_section,
    format_commit_message,
)


_TRIAGE_MD = """\
## Classification
patch-error

## Platform
DragonFly

## Root Cause
The bundled patch no longer applies — upstream renamed the function
the patch targets, so the hunk context drifted.

## Evidence
- `Hunk #1 FAILED at 42.`
- `1 out of 1 hunk FAILED -- saving rejects to file foo.c.rej`

## Suggested Fix
Regenerate the patch against the new upstream.

## Confidence
high
"""


def test_md_section_extracts_full_body():
    rc = _md_section(_TRIAGE_MD, "Root Cause")
    assert rc.startswith("The bundled patch no longer applies")
    assert "hunk context drifted." in rc
    # Stops at the next heading.
    assert "Evidence" not in rc


def test_md_section_caps_length():
    long = "## H\n" + ("x" * 5000) + "\n"
    out = _md_section(long, "H", max_chars=100)
    assert out.endswith("…(truncated)")
    assert len(out) < 200


def test_md_section_absent_returns_blank():
    assert _md_section(_TRIAGE_MD, "Nonexistent") == ""
    assert _md_section(None, "Root Cause") == ""


def test_md_inline_first_nonempty_line():
    assert _md_inline(_TRIAGE_MD, "Classification") == "patch-error"
    assert _md_inline(_TRIAGE_MD, "Confidence") == "high"
    assert _md_inline(None, "Classification") == ""


_SAMPLE_DIFF = """\
diff --git a/devel/foo/Makefile b/devel/foo/Makefile
index 111..222 100644
--- a/devel/foo/Makefile
+++ b/devel/foo/Makefile
@@ -1,3 +1,4 @@
 PORTNAME=foo
+USES=gmake
-OLD=line
diff --git a/devel/foo/files/patch-x b/devel/foo/files/patch-x
new file mode 100644
--- /dev/null
+++ b/devel/foo/files/patch-x
@@ -0,0 +1,2 @@
+hunk one
+hunk two
"""


def test_diffstat_counts_files_and_lines():
    stat = _diffstat(_SAMPLE_DIFF)
    assert "2 files changed" in stat
    # +USES, +hunk one, +hunk two = 3 insertions; -OLD = 1 deletion.
    assert "+3/-1" in stat
    assert "`devel/foo/Makefile`" in stat
    assert "`devel/foo/files/patch-x`" in stat


def test_diffstat_empty_diff_returns_blank():
    assert _diffstat("") == ""


def test_commit_message_title_has_no_internal_target_jargon():
    title, _ = format_commit_message(origin="devel/foo", target="@2026Q2")
    assert title == "devel/foo: fix build failure on DragonFly"
    assert "@2026Q2" not in title


# --- the commit body: plain text, wrapped, change-scoped ------------------

def test_commit_body_wraps_at_72_columns():
    """poly-378. Measured on a delivered commit before the split: a
    1106-character line. git log indents by four, so 72 keeps it inside
    an 80-column terminal."""
    _, body = format_commit_message(
        origin="devel/foo",
        root_cause="word " * 400,
        patch_summary="fix " * 400,
    )
    over = [ln for ln in body.splitlines() if len(ln) > 72]
    assert not over, over[:2]


def test_commit_body_carries_no_markdown():
    _, body = format_commit_message(
        origin="devel/foo",
        root_cause="The `Makefile` invoked **gmake** without declaring it.",
        patch_summary="Add `USES=gmake`.",
    )
    for token in ("##", "> ", "- ", "`", "**"):
        assert token not in body, token
    # Stripping decoration must not eat the words it decorated.
    assert "Makefile" in body and "gmake" in body and "USES=gmake" in body


def test_commit_body_leaves_verbatim_blocks_intact():
    """Fenced and indented blocks are quoted build output. Re-flowing
    them silently alters recorded output, so they pass through even
    when over-long."""
    long_line = "cc: error: " + "x" * 120
    _, body = format_commit_message(
        origin="devel/foo",
        root_cause="Prose that is long enough to need wrapping. " * 4,
        patch_summary="```\n" + long_line + "\n```",
    )
    assert long_line in body, "verbatim line was altered"


def test_commit_body_excludes_provenance_and_disclosure():
    """The commit records authorship in its author/committer fields;
    restating it as prose is redundant. Cost and operator identity are
    review-time context, not tree history."""
    _, body = format_commit_message(
        origin="devel/foo",
        root_cause="Root cause prose.",
        patch_summary="Fix prose.",
    )
    for token in ("Generated by", "Operator:", "attempts=", "tokens=",
                  "Verified", "Provenance"):
        assert token not in body, token


def test_commit_body_degrades_without_prose():
    _, body = format_commit_message(origin="devel/foo", target="@2026Q2")
    assert "Automated fix for the build failure in devel/foo" in body
    assert body.endswith("\n")


# --- the PR body: markdown, full narrative --------------------------------

def test_pr_body_full_narrative():
    body = format_pr_body(
        origin="devel/foo", target="@2026Q2",
        operator="alice", model="opus", attempts=2, tokens=12345,
        verified_at="2026-05-28T10:00:00Z",
        diff_text=_SAMPLE_DIFF,
        patch_summary="Add USES=gmake to fix the build.",
        root_cause="The Makefile invoked gmake without declaring it.",
        classification="patch-error",
        confidence="high",
        evidence="- `gmake: command not found`",
    )
    assert "> Generated by the DragonFly agentic build-fix loop" in body
    assert "operator `alice`" in body
    assert "## Problem" in body
    assert "classified `patch-error`" in body
    assert "confidence `high`" in body
    assert "The Makefile invoked gmake without declaring it." in body
    assert "**Evidence:**" in body
    assert "gmake: command not found" in body
    assert "## Fix\n\nAdd USES=gmake to fix the build." in body
    assert "2 files changed, +3/-1" in body
    assert "for target `@2026Q2`." in body
    assert "Verified 2026-05-28T10:00:00Z." in body
    assert "- Operator: alice" in body
    assert "- Agent: model=opus attempts=2 tokens=12345" in body
    assert "Bundle:" not in body


def test_pr_body_carries_platform_notes_and_rebuild_status():
    """poly-378. These existed in triage.md/patch.md and were dropped.
    Notes is the load-bearing one: it is where triage records scope, and
    losing it once already sent a reviewer a per-port fix for a
    tree-wide cause."""
    body = format_pr_body(
        origin="x11-toolkits/pango", target="@2026Q3", operator="op",
        model=None, attempts=None, tokens=None, verified_at=None,
        platform="dragonfly-specific",
        notes="This will recur in any dsynth environment.",
        rebuild_status="success",
    )
    assert "platform `dragonfly-specific`" in body
    assert "## Notes" in body
    assert "This will recur in any dsynth environment." in body
    assert "Rebuild status: `success`." in body


def test_pr_body_omits_proposed_fix_operator_instructions():
    """proposed_fix.md's apply/verify sections embed a loopback tracker
    URL and in-bundle artifact paths. Nothing from it is lifted, so a
    public PR cannot leak an internal address."""
    body = format_pr_body(
        origin="devel/foo", target="@2026Q2", operator="op",
        model=None, attempts=None, tokens=None, verified_at=None,
        patch_summary="Fix.", root_cause="Cause.",
    )
    assert "127.0.0.1" not in body
    assert "Apply this fix" not in body
    assert "Audit trail" not in body


def test_pr_body_degrades_without_triage_or_patch_prose():
    body = format_pr_body(
        origin="devel/foo", target="@2026Q2", operator="alice",
        model=None, attempts=None, tokens=None, verified_at=None,
    )
    assert "## Problem" in body
    assert "The build failed on `@2026Q2`." in body
    assert "## Fix" in body
    assert "Automated fix for the build failure in `devel/foo`." in body
    assert "## What changed" not in body
    assert "classified" not in body
    assert "## Notes" not in body


def _write_toml(tmp_path: Path, text: str) -> Path:
    p = tmp_path / "delivery.toml"
    p.write_text(text)
    return p


def test_config_defaults_committer_identity(tmp_path):
    cfg = load_delivery_config(
        _write_toml(tmp_path, """
[provider]
type = "github"
repo = "DragonFlyBSD/DeltaPorts"
clone_dir = "/tmp/clone"
"""),
        env={"DPORTSV3_DELIVERY_TOKEN": "tok"},
    )
    assert cfg.committer_name == "Fred [bot]"
    assert cfg.committer_email == "github@dragonflybsd.org"


def test_config_committer_identity_override(tmp_path):
    cfg = load_delivery_config(
        _write_toml(tmp_path, """
[provider]
type = "github"
repo = "DragonFlyBSD/DeltaPorts"
clone_dir = "/tmp/clone"
committer_name = "Custom Bot"
committer_email = "custom@example.org"
"""),
        env={"DPORTSV3_DELIVERY_TOKEN": "tok"},
    )
    assert cfg.committer_name == "Custom Bot"
    assert cfg.committer_email == "custom@example.org"
